-- DDL do projeto DimDim (Azure SQL Database)
-- Reexecutável: só cria o que ainda não existe (a aplicação roda este arquivo ao iniciar).
-- Para recriar do zero, rode antes manualmente:
--   DROP TABLE dbo.TRANSACAO; DROP TABLE dbo.CLIENTE;

-- Tabela MASTER
IF OBJECT_ID('dbo.CLIENTE', 'U') IS NULL
CREATE TABLE dbo.CLIENTE (
    ID_CLIENTE  BIGINT IDENTITY(1,1) NOT NULL,
    NOME        NVARCHAR(100) NOT NULL,
    EMAIL       NVARCHAR(100) NOT NULL,
    DT_CADASTRO DATETIME2     NULL DEFAULT SYSDATETIME(),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT UQ_CLIENTE_EMAIL UNIQUE (EMAIL)
);

-- Tabela DETAIL
IF OBJECT_ID('dbo.TRANSACAO', 'U') IS NULL
CREATE TABLE dbo.TRANSACAO (
    ID_TRANSACAO BIGINT IDENTITY(1,1) NOT NULL,
    ID_CLIENTE   BIGINT        NOT NULL,
    TIPO         NVARCHAR(20)  NOT NULL,
    VALOR        DECIMAL(12,2) NOT NULL,
    DT_TRANSACAO DATETIME2     NULL DEFAULT SYSDATETIME(),
    CONSTRAINT PK_TRANSACAO PRIMARY KEY (ID_TRANSACAO),
    CONSTRAINT FK_TRANSACAO_CLIENTE FOREIGN KEY (ID_CLIENTE)
        REFERENCES dbo.CLIENTE (ID_CLIENTE),
    CONSTRAINT CK_TRANSACAO_VALOR CHECK (VALOR > 0)
);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_TRANSACAO_CLIENTE')
CREATE INDEX IX_TRANSACAO_CLIENTE ON dbo.TRANSACAO (ID_CLIENTE);
