-- DDL do projeto DimDim (Azure SQL Database)

IF OBJECT_ID('dbo.TRANSACAO', 'U') IS NOT NULL DROP TABLE dbo.TRANSACAO;
IF OBJECT_ID('dbo.CLIENTE', 'U')   IS NOT NULL DROP TABLE dbo.CLIENTE;

-- Tabela MASTER
CREATE TABLE dbo.CLIENTE (
    ID_CLIENTE  BIGINT IDENTITY(1,1) NOT NULL,
    NOME        NVARCHAR(100) NOT NULL,
    EMAIL       NVARCHAR(100) NOT NULL,
    DT_CADASTRO DATETIME2     NULL DEFAULT SYSDATETIME(),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT UQ_CLIENTE_EMAIL UNIQUE (EMAIL)
);

-- Tabela DETAIL
CREATE TABLE dbo.TRANSACAO (
    ID_TRANSACAO BIGINT IDENTITY(1,1) NOT NULL,
    ID_CLIENTE   BIGINT        NOT NULL,
    TIPO         NVARCHAR(20)  NOT NULL,   -- PIX, CREDITO, DEBITO...
    VALOR        DECIMAL(12,2) NOT NULL,
    DT_TRANSACAO DATETIME2     NULL DEFAULT SYSDATETIME(),
    CONSTRAINT PK_TRANSACAO PRIMARY KEY (ID_TRANSACAO),
    CONSTRAINT FK_TRANSACAO_CLIENTE FOREIGN KEY (ID_CLIENTE)
        REFERENCES dbo.CLIENTE (ID_CLIENTE),
    CONSTRAINT CK_TRANSACAO_VALOR CHECK (VALOR > 0)
);

CREATE INDEX IX_TRANSACAO_CLIENTE ON dbo.TRANSACAO (ID_CLIENTE);
